services:

  btsplay-laravel:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: final
    image: btsplay-app:prod
    container_name: btsplay-laravel
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: prod
    working_dir: /var/www
    volumes:
      - ./.env.prod:/var/www/.env
      - /k/Archivage/H264:/mnt/archivage:z
      - /k/Archivage/Thumbnails:/mnt/miniatures:z
    networks:
      - app-network
    depends_on:
      - btsplay-mysql

  btsplay-queue:
    image: btsplay-app:prod
    container_name: btsplay-queue
    restart: unless-stopped
    entrypoint: []
    command: ["php", "artisan", "queue:work", "--tries=3", "--timeout=180", "--sleep=3", "--max-jobs=1000"]
    environment:
      SERVICE_NAME: queue
      SERVICE_TAGS: prod
    working_dir: /var/www
    volumes:
      - ./.env.prod:/var/www/.env
      - /c/Archivage/H264:/mnt/archivage:z
      - /c/Archivage/Thumbnails:/mnt/miniatures:z
    networks:
      - app-network
    depends_on:
      - btsplay-laravel

  btsplay-nginx:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: nginx
    container_name: btsplay-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - btsplay-mysql
      - btsplay-laravel

  btsplay-mysql:
    image: mysql:5.7
    container_name: btsplay-mysql
    restart: unless-stopped
    env_file: .env.prod
    volumes:
      - dbdata-prod:/var/lib/mysql:z
    networks:
      - app-network

  btsplay-phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    container_name: btsplay-phpmyadmin
    environment:
      PMA_HOST: btsplay-mysql
    ports:
      - "8001:80"
    networks:
      - app-network
    depends_on:
      - btsplay-mysql

networks:
  app-network:
    driver: bridge

volumes:
  dbdata-prod:
    driver: local
